### PR TITLE
Remove extra white space

### PR DESCRIPTION
**Pull request by jonatack**
Hi Adam! Enjoying your book and following along with the code. Cheers :)

### CODE REVIEW

**Comment by adamtornhill** [comment]
Thanks a lot! I'm glad you like the book. And thanks for the whitespace clean-up!

**Comment by ghost** [comment]
@adamtornhill I guess your book really inspires a lot of people who'd like to try some web programming in Common Lisp. Last year I read this book and then I read all your articles on your blog. Really learn a lot of from your work. 
Interestingly, I was then chosen to be an exchange student to go to Sweden. Those two things kind of causal :-D haha, anyway, great book and ideas and Sweden is so beautiful!

**Comment by jonatack** [comment]
Thanks! And I second @macdavid313 's comment. Looking forward to learning more Lisp :+1:

**Comment by adamtornhill** [comment]
Thanks @macdavid313 for your kind words! That's why I keep doing this stuff. And sharing is a great way to learn more yourself.

I'm glad that you enjoy Sweden. It's indeed beautiful - I just wish it was some degrees warmer here :)

**Pull request merged**
